/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Qvi
 */
public class AddMember extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddMember
     */
    public AddMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        amAdd = new javax.swing.JButton();
        amUpdate = new javax.swing.JButton();
        amDelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        amName = new javax.swing.JTextField();
        amUID = new javax.swing.JTextField();
        amMID = new javax.swing.JTextField();
        amMail = new javax.swing.JTextField();
        amCN = new javax.swing.JTextField();
        amMT = new javax.swing.JComboBox<>();
        amGender = new javax.swing.JComboBox<>();
        amBd = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        amA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(580, 410));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 394, 578, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setText("Add Member");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, 40));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 60));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("Name: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setText("Member ID: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("Gender: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("Birthday: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("Member Type: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setText("Address: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setText("Email: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setText("Contact No: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setText("UID: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        amAdd.setText("Add");
        amAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amAddActionPerformed(evt);
            }
        });
        getContentPane().add(amAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 70, -1));

        amUpdate.setText("Update");
        getContentPane().add(amUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 70, -1));

        amDelete.setText("Delete");
        getContentPane().add(amDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 70, -1));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 110, 230));
        getContentPane().add(amName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));
        getContentPane().add(amUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, -1));
        getContentPane().add(amMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));
        getContentPane().add(amMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 170, -1));
        getContentPane().add(amCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 170, -1));

        amMT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Student", "Teacher", "Official" }));
        getContentPane().add(amMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, -1));

        amGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        getContentPane().add(amGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 130, -1));

        amBd.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                amBdOnSelectionChange(evt);
            }
        });
        getContentPane().add(amBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 130, -1));

        amA.setColumns(20);
        amA.setRows(5);
        jScrollPane1.setViewportView(amA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, 90));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 580, 300));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 330));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -22, 578, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amAddActionPerformed

    private void amBdOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_amBdOnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_amBdOnSelectionChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea amA;
    private javax.swing.JButton amAdd;
    private datechooser.beans.DateChooserCombo amBd;
    private javax.swing.JTextField amCN;
    private javax.swing.JButton amDelete;
    private javax.swing.JComboBox<String> amGender;
    private javax.swing.JTextField amMID;
    private javax.swing.JComboBox<String> amMT;
    private javax.swing.JTextField amMail;
    private javax.swing.JTextField amName;
    private javax.swing.JTextField amUID;
    private javax.swing.JButton amUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
